spring.application.name=b2b-manager
spring.datasource.url=jdbc:mysql://localhost:3306/laundry_db?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=Dktnxk1004!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true