# 1. 콘솔(표준 출력)에 로그를 찍겠다고 강제 지정
appender=com.p6spy.engine.spy.appender.StdoutLogger

# 2. 한 줄로 깔끔하게 출력하기 위한 포맷 설정
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=%(currentTime) | p6spy | %(sqlSingleLine)

# 3. 날짜/시간 형식
dateformat=yyyy-MM-dd HH:mm:ss